const { Car } = require('../models');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await Car.bulkCreate([
      {
        id: 1,
        brand: 'toyota',
        model: 'landcruser',
        engine: 'disel',
        year: 1972,
        mileage: 400_000,
        power: 228,
        price: 322,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'cool ta4ka',
      },
      {
        id: 2,
        brand: 'UAZ',
        model: 'uazik',
        engine: 'disel',
        year: 2000,
        mileage: 10_000,
        power: 777,
        price: 1000_000,
        driveUnit: 'full privod',
        transmission: 'transmissiya',
        description: 'top ta4ka',
      },
      {
        id: 3,
        brand: 'volvo',
        model: 'cx70',
        engine: 'benz',
        year: 2012,
        mileage: 100_000,
        power: 100,
        price: 1500_000,
        driveUnit: 'zad',
        transmission: 'transmissiya',
        description: 'strogaya ta4ka',
      },
      {
        id: 4,
        brand: 'bmw',
        model: '5',
        engine: 'gaz',
        year: 2025,
        mileage: 0,
        power: 999,
        price: 1000,
        driveUnit: 'kak zaho4esh',
        transmission: 'transmissiya',
        description: 'unveliveble ta4ka',
      },
      {
        id: 5,
        brand: 'lada',
        model: 'vesta',
        engine: 'benz',
        year: 2017,
        mileage: 50_000,
        power: 106,
        price: 600_000,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'dream',
      },
      {
        id: 6,
        img: '/img/car6.jpeg',
        brand: 'toyota',
        model: 'landcruser',
        engine: 'disel',
        year: 1972,
        mileage: 400_000,
        power: 228,
        price: 322,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'cool ta4ka',
      },
      {
        id: 7,
        img: '/img/car7.jpeg',
        brand: 'UAZ',
        model: 'uazik',
        engine: 'disel',
        year: 2000,
        mileage: 10_000,
        power: 777,
        price: 1000_000,
        driveUnit: 'full privod',
        transmission: 'transmissiya',
        description: 'top ta4ka',
      },
      {
        id: 8,
        img: '/img/car8.jpeg',
        brand: 'volvo',
        model: 'cx70',
        engine: 'benz',
        year: 2012,
        mileage: 100_000,
        power: 100,
        price: 1500_000,
        driveUnit: 'zad',
        transmission: 'transmissiya',
        description: 'strogaya ta4ka',
      },
      {
        id: 9,
        img: '/img/car9.jpeg',
        brand: 'bmw',
        model: '5',
        engine: 'gaz',
        year: 2025,
        mileage: 0,
        power: 999,
        price: 1000,
        driveUnit: 'kak zaho4esh',
        transmission: 'transmissiya',
        description: 'unveliveble ta4ka',
      },
      {
        id: 10,
        img: '/img/car10.jpeg',
        brand: 'lada',
        model: 'vesta',
        engine: 'benz',
        year: 2017,
        mileage: 50_000,
        power: 106,
        price: 600_000,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'dream',
      },
      {
        id: 11,
        img: '/img/car11.jpeg',
        brand: 'bmw',
        model: '5',
        engine: 'gaz',
        year: 2025,
        mileage: 0,
        power: 999,
        price: 1000,
        driveUnit: 'kak zaho4esh',
        transmission: 'transmissiya',
        description: 'unveliveble ta4ka',
      },
      {
        id: 12,
        img: '/img/car12.jpeg',
        brand: 'lada',
        model: 'vesta',
        engine: 'benz',
        year: 2017,
        mileage: 50_000,
        power: 106,
        price: 600_000,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'dream',
      },
    ]);
  },

  async down(queryInterface) {
    await Car.destroy({ truncate: { cascade: true } });
  },
};
