/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    const carsData = [
      {
        brand: 'toyota',
        model: 'landcruser',
        engine: 'disel',
        year: 1972,
        mileage: 400_000,
        power: 228,
        price: 322,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'cool ta4ka',
      },
      {
        brand: 'UAZ',
        model: 'uazik',
        engine: 'disel',
        year: 2000,
        mileage: 10_000,
        power: 777,
        price: 1000_000,
        driveUnit: 'full privod',
        transmission: 'transmissiya',
        description: 'top ta4ka',
      },
      {
        brand: 'volvo',
        model: 'cx70',
        engine: 'benz',
        year: 2012,
        mileage: 100_000,
        power: 100,
        price: 1500_000,
        driveUnit: 'zad',
        transmission: 'transmissiya',
        description: 'strogaya ta4ka',
      },
      {
        brand: 'bmw',
        model: '5',
        engine: 'gaz',
        year: 2025,
        mileage: 0,
        power: 999,
        price: 1000,
        driveUnit: 'kak zaho4esh',
        transmission: 'transmissiya',
        description: 'unveliveble ta4ka',
      },
      {
        brand: 'lada',
        model: 'vesta',
        engine: 'benz',
        year: 2017,
        mileage: 50_000,
        power: 106,
        price: 600_000,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'dream',
      },
      {
        brand: 'toyota',
        model: 'landcruser',
        engine: 'disel',
        year: 1972,
        mileage: 400_000,
        power: 228,
        price: 322,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'cool ta4ka',
      },
      {
        brand: 'UAZ',
        model: 'uazik',
        engine: 'disel',
        year: 2000,
        mileage: 10_000,
        power: 777,
        price: 1000_000,
        driveUnit: 'full privod',
        transmission: 'transmissiya',
        description: 'top ta4ka',
      },
      {
        brand: 'volvo',
        model: 'cx70',
        engine: 'benz',
        year: 2012,
        mileage: 100_000,
        power: 100,
        price: 1500_000,
        driveUnit: 'zad',
        transmission: 'transmissiya',
        description: 'strogaya ta4ka',
      },
      {
        brand: 'bmw',
        model: '5',
        engine: 'gaz',
        year: 2025,
        mileage: 0,
        power: 999,
        price: 1000,
        driveUnit: 'kak zaho4esh',
        transmission: 'transmissiya',
        description: 'unveliveble ta4ka',
      },
      {
        brand: 'lada',
        model: 'vesta',
        engine: 'benz',
        year: 2017,
        mileage: 50_000,
        power: 106,
        price: 600_000,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'dream',
      },
      {
        brand: 'bmw',
        model: '5',
        engine: 'gaz',
        year: 2025,
        mileage: 0,
        power: 999,
        price: 1000,
        driveUnit: 'kak zaho4esh',
        transmission: 'transmissiya',
        description: 'unveliveble ta4ka',
      },
      {
        brand: 'lada',
        model: 'vesta',
        engine: 'benz',
        year: 2017,
        mileage: 50_000,
        power: 106,
        price: 600_000,
        driveUnit: 'peredniy',
        transmission: 'transmissiya',
        description: 'dream',
      },
    ];
    const cars = carsData.map((car) => ({
      ...car,
      createdAt: new Date(),
      updatedAt: new Date(),
    }));
    await queryInterface.bulkInsert('Cars', cars);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Cars');
  },
};
